# dbt_project.yml
name: 'tipico_data_modeling'
version: '1.0.0'
config-version: 2

profile: 'redshift'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  tipico_data_modeling:
    schema: "sumanth_atluri"
    materialized: table
