name: 'tipico_events'
version: '1.0.0'
config-version: 2

profile: 'redshift'

models:
  tipico_events:
    +materialized: table
    raw_tipico_events:
      +column_types:
        json_data: STRING
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: tipico_marts
    core:
      +schema: tipico_marts

source-paths: ["models"]
target-path: "target"

seeds: 
  +schema: seeds

require-dbt-version: [">=1.0.0", "<2.0.0"]

profiles:
  redshift:
    target: dev
    outputs:
      dev:
        type: redshift
        host: manual-dwh-candidatetests.258845600139.us-east-1.redshift-serverless.amazonaws.com
        port: 5439
        user: sumanth_atluri
        password: Fn59_fwn!bAf_QP
        dbname: dev
        schema: sumanth_atluri
        threads: 4
