name: 'tipico_events'
version: '1.0.0'
config-version: 2

models:
  tipico_events:
    +materialized: table
    staging:
      +materialized: view
      raw_tipico_events:
        +column_types:
          data: STRING
    marts:
      +materialized: table
      core:
        +schema: tipico_marts

model-paths: ["models"]

vars:
  redshift:
    host: manual-dwh-candidatetests.258845600139.us-east-1.redshift-serverless.amazonaws.com
    port: 5439
    database: dev
    user: sumanth_atluri
    password: Fn59_fwn!bAf_QP
    schema: sumanth_atluri

target:
  type: redshift
  host: "{{ var('redshift:host') }}"
  port: "{{ var('redshift:port') }}"
  database: "{{ var('redshift:database') }}"
  user: "{{ var('redshift:user') }}"
  password: "{{ var('redshift:password') }}"
  schema: "{{ var('redshift:schema') }}"
