name: 'tipico_events'
version: '1.0.0'
config-version: 2

models:
  tipico_events:
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: tipico_marts

model-paths: ["models"]
target-path: "target"

require-dbt-version: [">=1.0.0", "<2.0.0"]
