name: 'tipico_events'
version: '1.0.0'
config-version: 2

models:
  tipico_events:
    +materialized: table
    raw_tipico_events:
      +column_types:
        data: STRING
    staging:
      +materialized: view
    marts:
      +materialized: table
      core:
        +schema: tipico_marts

model-paths: ["models"]
