# dbt_project.yml
name: 'tipico_data_modeling'
version: '1.0.0'
config-version: 2

profile: 'redshift'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  tipico_data_modeling:
    schema: "sumanth_atluri"
    materialized: table

seeds:
  tipico_data_modeling:
    schema: "sumanth_atluri"
