name: 'tipico_events'
version: '1.0.0'
config-version: 2

vars:
  redshift_host: manual-dwh-candidatetests.258845600139.us-east-1.redshift-serverless.amazonaws.com
  redshift_port: 5439
  redshift_user: sumanth_atluri
  redshift_password: 'Fn59_fwn!bAf_QP'

models:
  tipico_events:
    +materialized: table
  staging:
    +materialized: view
  raw_tipico_events:
    +column_types:
      data: STRING
  marts:
    +materialized: table
    core:
      +schema: tipico_marts

model-paths: ["models"]

target:
  type: redshift
  host: '{{ var("redshift_host") }}'
  port: '{{ var("redshift_port") }}'
  database: dev
  user: '{{ var("redshift_user") }}'
  password: '{{ var("redshift_password") }}'
  schema: sumanth_atluri

packages:
  - package: dbt-labs/redshift
    version: 1.5.8
