tipico_events:
  target: dev
  outputs:
    dev:
      type: redshift
      host: manual-dwh-candidatetests.258845600139.us-east-1.redshift-serverless.amazonaws.com
      port: 5439
      database: dev
      user: sumanth_atluri
      password: Fn59_fwn!bAf_QP
      schema: sumanth_atluri
